apiVersion: v1
kind: ConfigMap
metadata:
  name: sputnik-v2-configmap
data:
  NEAR_ENV: "{{ .Values.environment.near_env }}"
  NEAR_CONTRACT_NAME: "{{ .Values.environment.near_contract_name }}"
  NEAR_TOKEN_FACTORY_CONTRACT_NAME: "{{ .Values.environment.near_token_factory_contract_name }}"
  NEAR_BRIDGE_TOKEN_FACTORY_CONTRACT_NAME: "{{ .Values.environment.near_bridge_token_factory_contract_name }}"
  ADMIN_ACCOUNTS: "{{ .Values.environment.admin_accounts }}"
  NEAR_CREDENTIALS_DIR: ".near-credentials"
  LOG_LEVELS: "log,warn,error"
