test:
  env: ${TEST_ENV:dev}
  accountId: testdao2.testnet
#  accountId: automation-01.testnet
  dao1: test-dao-1641395769436.sputnikv2.testnet
  dao2: test-dao-1647325144337.sputnikv2.testnet
  proposal1: test-dao-1641395769436.sputnikv2.testnet-911
#  bounty1: test-dao-1641395769436.sputnikv2.testnet-1578
  approved.bounty.proposal1: test-dao-1641395769436.sputnikv2.testnet-2306
  approved.bounty.proposal2: test-dao-1641395769436.sputnikv2.testnet-2308
  bounty1: test-dao-1641395769436.sputnikv2.testnet-2
  bounty2: test-dao-1641395769436.sputnikv2.testnet-3
  aggregation.timeout: ${TEST_AGG_TIMEOUT:20}

accounts:
  account1:
    accountId: testdao2.testnet
    publicKey: ed25519:8kqG6dyAheDqzoZh4hk9HbjBngG6fTnCD4zTw6sVud9K
    signature: JJoq7fvBh6JXH9kVXtV0SoeT3YDSm9Gr6Ug4cmJNXAtuU2bZFu9/8bN26xw7MwYBRdWTZr2v81JZDO9zYaE8Dg==
    token: dGVzdGRhbzIudGVzdG5ldHxlZDI1NTE5OjhrcUc2ZHlBaGVEcXpvWmg0aGs5SGJqQm5nRzZmVG5DRDR6VHc2c1Z1ZDlLfEpKb3E3ZnZCaDZKWEg5a1ZYdFYwU29lVDNZRFNtOUdyNlVnNGNtSk5YQXR1VTJiWkZ1OS84Yk4yNnh3N013WUJSZFdUWnIydjgxSlpETzl6WWFFOERnPT0=

  account2:
    accountId: automation-01.testnet
    publicKey: ed25519:62vv9ViLDYnLtMZBUBgT8h5bB5yHLWYMbeeYKAVfChQF
    signature: FLRzkKGeSdDUimtvkk4E7qMyViESPHxkMvBR1fTLKxfOCJqDWMYXciutO9O9nOJrXzp1d0u/aoR6kG4qwvHXCA==
    token: YXV0b21hdGlvbi0wMS50ZXN0bmV0fGVkMjU1MTk6NjJ2djlWaUxEWW5MdE1aQlVCZ1Q4aDViQjV5SExXWU1iZWVZS0FWZkNoUUZ8RkxSemtLR2VTZERVaW10dmtrNEU3cU15VmlFU1BIeGtNdkJSMWZUTEt4Zk9DSnFEV01ZWGNpdXRPOU85bk9Kclh6cDFkMHUvYW9SNmtHNHF3dkhYQ0E9PQ==

  account3:
    accountId: astro-automation-reserved6.testnet
    publicKey: ed25519:GQTTiPkDm53Fqg8S8eHVdHLKJWXzWEuCzACsBSDedLyH
    signature: 0GGz4qgFQrZlpDcJlW96g514/qz7HI6zPyRygpbghwP3u3S7LYigrE2HCAhX2DbW1gx0Ny+2nYAKMHPBu6p3Dw==
    token: YXN0cm8tYXV0b21hdGlvbi1yZXNlcnZlZDYudGVzdG5ldHxlZDI1NTE5OkdRVFRpUGtEbTUzRnFnOFM4ZUhWZEhMS0pXWHpXRXVDekFDc0JTRGVkTHlIfDBHR3o0cWdGUXJabHBEY0psVzk2ZzUxNC9xejdISTZ6UHlSeWdwYmdod1AzdTNTN0xZaWdyRTJIQ0FoWDJEYlcxZ3gwTnkrMm5ZQUtNSFBCdTZwM0R3PT0=