apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "sputnik-v2-api.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-development"
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ include "sputnik-v2-api.fullname" . }}-tls-secret
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ include "sputnik-v2-api.fullname" . }}
            servicePort: 80
